development:
  adapter: postgresql
  encoding: unicode
  database: reed_portfolio_development
  pool: 5
  username: reedns
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: reed_portfolio_development
  pool: 5
  username: reedns
