development:
  adapter: postgresql
  encoding: unicode
  database: gem_store_rails_development
  pool: 5
  username: reedns
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gem_store_rails_development
  pool: 5
  username: reedns
