# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9d6b121848e30dbda3b0a517a266851b360ed7431812db646c0da1302af5c098c9652ee94af1c09340591ba39db846fa3aac7cb48eb2190e2dd9dffed134825

test:
  secret_key_base: 56d90a1a5c03c6f0db26c71696cb18d85582f1e9a2de1b7a4b372ec3022d67d2ca6957fd0fdb0748213e60d0c4122e75adb6f0d9916c4a287e8bb900c79fd3e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
